### ISSUE TITLE
add atmel programmer/debugger tools

### ISSUE THREAD

**Issue by syddo** [abcminiuser/dmbs#16]
hi @abcminiuser , how do I add some programmer/debugger tools like the ATPowerDebugger or the JTAG ICE Mk3?

**Comment by abcminiuser** [comment]
The ATPROGRAM module should already take care of it, since those are driven by Atmel's `atbackend` utility inside Atmel Studio. Just set `ATPROGRAM_PROGRAMMER` and `ATPROGRAM_INTERFACE` in your makefile, as documented [here](https://github.com/abcminiuser/dmbs/blob/master/DMBS/atprogram.mk).

If you run `atbackend` manually you should be able to get it to print out a list of known debugger tool names, such as `atmelice` or (I assume) something like `powerdebugger`.

**Comment by syddo** [comment]
Thanks Dean @abcminiuser !
