### ISSUE TITLE
usage recommendation

### ISSUE THREAD

**Issue by nerdralph** [abcminiuser/dmbs#4]
How do you recommend using dmbs?
I've used git submodules.
I see for lufa you copied dmbs, prefixing most of the variables with lufa_.  This would seem to make it hard to incorporate improvements to dmbs into lufa.
Another option would seem to be forking and modifying the template.
Perhaps the readme could include a recommendation or list of options.

**Comment by abcminiuser** [comment]
Actually, I started off making the LUFA build system, and I eventually spun it off as a standalone project rather than the other way around. I'll have a look into integrating it into LUFA with some extensions using submodules to avoid duplication.

It should be OK to use DMBS standalone (upgrade by checking in a new dump from master) or you can use Git Submodules/Subtrees.

**Comment by abcminiuser** [comment]
I've created an issue on LUFA here at https://github.com/abcminiuser/lufa/issues/67 to track DMBS integration.

**Comment by NicoHood** [comment]
I also came to the situation that I need a simple makefile for an avr project. However I want things like size view and set F_CPU etc in the makefile (like I am used to with lufa). So I remember you have this project still laying around.

Would you recommend to use it, since its 2 years "old" now. A bit more dokumentation about the state (alpha, beta, usable) would be nice. So its not clear to me if DMBS work was left off or finished.

Edit:
After a few quick tests I have to say: great job!
I'd really like to see this continued, cause its THE avr makefile you want to use.

**Comment by abcminiuser** [comment]
> Would you recommend to use it, since its 2 years "old" now. A bit more dokumentation about the state (alpha, beta, usable) would be nice. So its not clear to me if DMBS work was left off or finished.

I'll update the README.md, but I consider it production ready. It's the core of the LUFA build system just split out, which has been in use for years now without issue.

Regarding the documentation, since I'm migrating LUFA to it very soon I'll be shifting the existing documentation from there into DMBS, to give more human friendly HTML output.

**Comment by NicoHood** [comment]
I've been searching some settings inside the sources (.mk files). If that'd be documented it would be perfect!

A few more examples would be nice.

I also added avrdude support. However for the UNO and Mega you need different settings (like the mega needs the -D option for avrdude and another protocol). An example for an automated target detection would be nice, to se the avrdude settings on this. This can be done in the makefile for sure, since not everybody uses arduino bootloaders as base. Thatswhy as example and not inside the core.

I've been coding a bit now and I noticed avr-gcc just pulls in any function that i wrote, even if its not used. I guess thats more a general question, but you might add such information to the readme or as example to show how to fix it. (I havent fixed it yet, any help appreciated).

**Comment by NicoHood** [comment]
Oh I just noticed a few things:

You are not using submodules. Yes this avoids a simple .zip download, but you can provide it via the github releases:
https://github.com/abcminiuser/lufa/releases

There is still a wrapper around DMBS and not the other way around (DMBS includes LUFA stuff).
Lets say I want to do a project with some IR Remote to USB translation (and other stuff). Then I want to start a DMBS project from scratch. I first write some basic debug stuff and the IR decoder. After this works I want to pull in the LUFA project as kind of DMBS module.

That from the POV from a user like me. The advantage I am thinking of here is to make LUFA more pluggable to add into several projects. Possibly also add some special switches to use VUSB and LUFA dynamically for some project. But the idea is not to use a lufa makefile that bases on DMBS. Rather a DMBS that uses LUFA as kind of module/library.

**Comment by NicoHood** [comment]
#5 fixes this somehow.

**Comment by abcminiuser** [comment]
OK, so I've gone and got married, and I'm getting some free time back to look at this and other pending issues.

@NicoHood: Yes, it's a little inverted at the moment in that branch, with LUFA wrapper DMBS. However, it's the neatest solution I have for now that doesn't break existing LUFA projects, so I think it's a good start. I'm a little worried about sitting around waiting indefinitely for a perfect solution, so I think it's in the community's best interest if I merge what I have for now (unless someone has an objection) and then we can figure out a better solution.

Pending issues will be:
1. How to re-invert the responsibility so that LUFA is provided as a DMBS extension
2. Whether to use submodules (I do like submodules, but I suspect people will be unhappy if they have to download both a LUFA zip file (or Git checkout) as well as DMBS and do some self-assembly
3. How to shift the DMBS documentation from LUFA into the DMBS project

So, unless someone raises a good strong counter point in the next few days, I'll merge in the DMBS branch to master and open up new separate issues for the above.

**Comment by NicoHood** [comment]
Yeah, merge it for now.
But we should invert the logic so dmbs includes lufa.

**Comment by abcminiuser** [comment]
Closing this now that the DMBS module documentation has been rolled into this repository, and that a PR exists to switch LUFA to DMBS (see https://github.com/abcminiuser/lufa/pull/79).
